### ISSUE TITLE
Not able to genrate Matrix by using OSRMdistance

### ISSUE THREAD

**Issue by nikhilve99** [sabas/OSRMdistance#3]
We tried using csv file and getting below error:

php OSRMextractData.php Matrix.csv out.csv
PHP Warning:  simplexml_load_file(): Matrix.csv:1: parser error : Start tag expected, '<' not found in /root/osrm/OSRMdistance/OSRMextractData.php on line 22
PHP Warning:  simplexml_load_file(): node,lat,lon in /root/osrm/OSRMdistance/OSRMextractData.php on line 22
PHP Warning:  simplexml_load_file(): ^ in /root/osrm/OSRMdistance/OSRMextractData.php on line 22
PHP Fatal error:  Uncaught Error: Call to a member function children() on boolean in /root/osrm/OSRMdistance/OSRMextractData.php:23
Stack trace:
#0 {main}

  thrown in /root/osrm/OSRMdistance/OSRMextractData.php on line 23

**another porint:
![matrix csv](https://cloud.githubusercontent.com/assets/3167200/19673676/9e1649b2-9a9f-11e6-90aa-a78a55f5a24c.png)
![matrix xml](https://cloud.githubusercontent.com/assets/3167200/19673679/a45d1184-9a9f-11e6-83e2-35e5d32d72c6.png)

**
i tried after converting my file csv to xml format , command executed but the out file i received was black except headers on file. 

kindly help to resolve the issue.

Regards
Nikhil

**Comment by sabas** [comment]
Hi,
OSRMextractdata isn't necessary if you've already an input formatted as csv triples
Simply execute php OSRMdistance.php in.csv out.csv
